name: Test and Release

on:
  push:
    tags:
      - v**

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install packages
        run: sudo apt-get install build-essential netpbm

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run test
        run: make test

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Publish
        env:
          PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
        run: pio pkg publish --no-interactive

      - name: Release
        uses: softprops/action-gh-release@v2
